name: Test PRs

on:
  pull_request:
    paths-ignore:
      - 'meta/**'
    branches-ignore:
      - import-dsd
      - import-word-templates
      - weblate-sdg-cambodia-dsd-series

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Test and build data
      run: |
        python scripts/check_data.py
        python scripts/build_data.py
